Convert gl-fix-permiessions from bash to sh script

diff --git a/backend/bin/gl-fix-permissions b/backend/bin/gl-fix-permissions
--- a/backend/bin/gl-fix-permissions
+++ b/backend/bin/gl-fix-permissions
@@ -1,8 +1,9 @@
-#!/bin/bash
+#!/bin/sh
 
-if [[ $EUID -ne 0 ]]; then
-   echo "This script must be run as root" 1>&2
-   exit 1
+# user permission check
+if [ ! $(id -u) = 0 ]; then
+    echo "Error: GlobaLeaks install script must be runned by root"
+    exit 1
 fi
 
 if ! id -u globaleaks >/dev/null 2>&1; then
