amendment to previous commit: simplified iptables support checking.

diff --git a/debian/globaleaks.init b/debian/globaleaks.init
--- a/debian/globaleaks.init
+++ b/debian/globaleaks.init
@@ -83,24 +83,6 @@ SCRIPTNAME=$0
 
 GLBACKEND_PIDFILE=${WORKING_DIR}/twistd.pid
 
-DO () {
-    if [ -z "$3" ]; then
-        CMD=$1
-    else
-        CMD=$3
-    fi
-    log_action_begin_msg "Running: \"$CMD\"... "
-    $1 &>${BUILD_LOG}
-    if [ $? -eq $2 ]; then
-        log_action_end_msg 0 "SUCCESS"
-    else
-        log_action_end_msg 1 "FAIL"
-        echo "COMBINED STDOUT/STDERR OUTPUT OF FAILED COMMAND:"
-        cat ${BUILD_LOG}
-        exit 1
-    fi
-}
-
 read_pid()
 {
     if [ -e ${GLBACKEND_PIDFILE} ]; then
@@ -132,6 +114,12 @@ network_sandboxing_start()
 
     check_iptables
 
+    iptables -nvL 2<&-
+    if [ $? -eq 0 ]; then
+        log_action_end_msg 1 "missing iptables support"
+        return
+    fi
+
     iptables -L | grep ${USER} >/dev/null 2<&-
     if [ $? -eq 0 ]; then
         log_action_end_msg 0 "already enabled."
@@ -143,19 +131,19 @@ network_sandboxing_start()
     do
         for IP_SRC in "${ALLOWED_SRC_IP[@]}"
         do
-            DO "iptables -A INPUT -p tcp -d ${IP_DST} --dport ${LISTENING_PORT} -s ${IP_SRC} -j ACCEPT" "0"
+            iptables -A INPUT -p tcp -d ${IP_DST} --dport ${LISTENING_PORT} -s ${IP_SRC} -j ACCEPT
         done
-        DO "iptables -A INPUT -p tcp -d ${IP_DST} --dport ${LISTENING_PORT}  -j DROP" "0"
+        iptables -A INPUT -p tcp -d ${IP_DST} --dport ${LISTENING_PORT}  -j DROP
     done
 
     # OUTBOUND
     # All outbound connections from GlobaLeaks goes trough Tor
-    DO "iptables -t nat -A OUTPUT ! -o lo -p tcp -m owner --uid-owner ${USER} -m tcp -j REDIRECT --to-ports ${TORTRANSPORT}" "0"
-    DO "iptables -t nat -A OUTPUT ! -o lo -p udp -m owner --uid-owner ${USER} -m udp --dport 53 -j REDIRECT --to-ports ${TORDNSPORT}" "0"
-    DO "iptables -t filter -A OUTPUT -p tcp -m owner --uid-owner ${USER} -m tcp --dport ${TORTRANSPORT} -j ACCEPT" "0"
-    DO "iptables -t filter -A OUTPUT -p udp -m owner --uid-owner ${USER} -m udp --dport 53 -j ACCEPT" "0"
-    DO "iptables -t filter -A OUTPUT -p tcp -m owner --uid-owner ${USER} -m tcp -d 127.0.0.1 --dport ${TORSOCKSPORT} -j ACCEPT" "0"
-    DO "iptables -t filter -A OUTPUT ! -o lo -m owner --uid-owner ${USER} -j DROP" "0"
+    iptables -t nat -A OUTPUT ! -o lo -p tcp -m owner --uid-owner ${USER} -m tcp -j REDIRECT --to-ports ${TORTRANSPORT}
+    iptables -t nat -A OUTPUT ! -o lo -p udp -m owner --uid-owner ${USER} -m udp --dport 53 -j REDIRECT --to-ports ${TORDNSPORT}
+    iptables -t filter -A OUTPUT -p tcp -m owner --uid-owner ${USER} -m tcp --dport ${TORTRANSPORT} -j ACCEPT
+    iptables -t filter -A OUTPUT -p udp -m owner --uid-owner ${USER} -m udp --dport 53 -j ACCEPT
+    iptables -t filter -A OUTPUT -p tcp -m owner --uid-owner ${USER} -m tcp -d 127.0.0.1 --dport ${TORSOCKSPORT} -j ACCEPT
+    iptables -t filter -A OUTPUT ! -o lo -m owner --uid-owner ${USER} -j DROP
 
     log_action_end_msg 0
 }
@@ -177,19 +165,19 @@ network_sandboxing_stop()
     do
         for IP_SRC in "${ALLOWED_SRC_IP[@]}"
         do
-            DO "iptables -D INPUT -p tcp -d ${IP_DST} --dport ${LISTENING_PORT}  -s ${IP_SRC} -j ACCEPT" "0"
+            iptables -D INPUT -p tcp -d ${IP_DST} --dport ${LISTENING_PORT}  -s ${IP_SRC} -j ACCEPT
         done
-        DO "iptables -D INPUT -p tcp -d ${IP_DST} --dport ${LISTENING_PORT}  -j DROP" "0"
+        iptables -D INPUT -p tcp -d ${IP_DST} --dport ${LISTENING_PORT}  -j DROP
     done
 
     # OUTBOUND
     # All outbound connections from GlobaLeaks goes trough Tor
-    DO "iptables -t nat -D OUTPUT ! -o lo -p tcp -m owner --uid-owner ${USER} -m tcp -j REDIRECT --to-ports ${TORTRANSPORT}" "0"
-    DO "iptables -t nat -D OUTPUT ! -o lo -p udp -m owner --uid-owner ${USER} -m udp --dport 53 -j REDIRECT --to-ports ${TORDNSPORT}" "0"
-    DO "iptables -t filter -D OUTPUT -p tcp -m owner --uid-owner ${USER} -m tcp --dport ${TORTRANSPORT} -j ACCEPT"
-    DO "iptables -t filter -D OUTPUT -p udp -m owner --uid-owner ${USER} -m udp --dport 53 -j ACCEPT" "0"
-    DO "iptables -t filter -D OUTPUT -p tcp -m owner --uid-owner ${USER} -m tcp -d 127.0.0.1 --dport ${TORSOCKSPORT} -j ACCEPT" "0"
-    DO "iptables -t filter -D OUTPUT ! -o lo -m owner --uid-owner ${USER} -j DROP" "0"
+    iptables -t nat -D OUTPUT ! -o lo -p tcp -m owner --uid-owner ${USER} -m tcp -j REDIRECT --to-ports ${TORTRANSPORT}
+    iptables -t nat -D OUTPUT ! -o lo -p udp -m owner --uid-owner ${USER} -m udp --dport 53 -j REDIRECT --to-ports ${TORDNSPORT}
+    iptables -t filter -D OUTPUT -p tcp -m owner --uid-owner ${USER} -m tcp --dport ${TORTRANSPORT} -j ACCEPT
+    iptables -t filter -D OUTPUT -p udp -m owner --uid-owner ${USER} -m udp --dport 53 -j ACCEPT
+    iptables -t filter -D OUTPUT -p tcp -m owner --uid-owner ${USER} -m tcp -d 127.0.0.1 --dport ${TORSOCKSPORT} -j ACCEPT
+    iptables -t filter -D OUTPUT ! -o lo -m owner --uid-owner ${USER} -j DROP
 
     log_action_end_msg 0
 }
