Fix #958.
Provide a /etc/default/globaleaks.d mechanism, and do not hardfail if a default
configuration is not found.

diff --git a/debian/globaleaks.init b/debian/globaleaks.init
--- a/debian/globaleaks.init
+++ b/debian/globaleaks.init
@@ -24,11 +24,36 @@ NAME=$(basename $(readlink -nf $0))
 
 SCRIPTNAME=$0
 
-if test -e /etc/default/globaleaks ; then
-    . /etc/default/globaleaks
-else
-    echo "Error: missing globaleaks default file"
-    exit 0
+if test -e "/etc/default/globaleaks" ; then
+   . "/etc/default/globaleaks"
+fi
+
+if [ -d "/etc/default/globaleaks.d" ]; then
+   for i in "/etc/default/globaleaks.d/"*; do
+       if [ -f "$i" ]; then
+           ## If the last character is a ~, ignore that file, because it was created
+           ## by some editor, which creates backup files.
+           if [ "${i: -1}" = "~" ]; then
+               true "skip $i"
+               continue
+           fi
+           ## Skipping files such as .dpkg-old and .dpkg-dist.
+           if ( echo "$i" | grep -q ".dpkg-" ); then
+               true "skip $i"
+               continue
+           fi
+           bash_n_exit_code="0"
+           bash_n_output="$(bash -n "$i" 2>&1)" || { bash_n_exit_code="$?" ; true; };
+           if [ ! "$bash_n_exit_code" = "0" ]; then
+               echo "Invalid config file: $i
+bash_n_exit_code: $bash_n_exit_code
+bash_n_output:
+$bash_n_output" >&2
+               exit 1
+           fi
+           . "$i"
+       fi
+   done
 fi
 
 . /lib/init/vars.sh
@@ -211,7 +236,7 @@ do_start()
                     --loglevel=${LOGLEVEL}
                     --http-log=${HTTPLOG}"
 
-    
+
     if [ "${STORMDEBUG}" -eq "1" ]; then
         GLBACKEND_ARGS+=" --storm-debug"
     fi
