Require iptables as necessary component

diff --git a/debian/globaleaks.init b/debian/globaleaks.init
--- a/debian/globaleaks.init
+++ b/debian/globaleaks.init
@@ -94,9 +94,9 @@ network_sandboxing_start()
 {
     log_action_begin_msg "Enabling Globaleaks Network Sandboxing"
 
-    if ! which iptables >/dev/null 2>&1 ; then
-        echo "GlobaLeaks Network Sandboxing Failure: requires iptables"
-        return
+    if ! command -v iptables >/dev/null 2>&1  || ! command -v ip6tables >/dev/null 2>&1 ; then
+        log_failure_msg "GlobaLeaks Network Sandboxing Failure: requires iptables"
+        exit 1
     fi
 
     # remove all rules with the comment: "globaleaks-network-sandboxing"
@@ -118,55 +118,53 @@ network_sandboxing_start()
     fi
 
     # OUTBOUND
-    if [[ "$NETWORK_SANDBOXING" -eq "1" ]]; then
-        if [[ "$TOR_SANDBOXING" -eq "1" ]]; then
-            declare -a PORTS=("80" "443")
-            for PORT in "${PORTS[@]}"; do
-                iptables -m comment --comment "globaleaks" -A INPUT -p tcp -d 0.0.0.0/0 --dport $PORT -s 127.0.0.1 -j ACCEPT
-                iptables -m comment --comment "globaleaks" -A INPUT -p tcp -d 0.0.0.0/0 --dport $PORT -j DROP
-                ip6tables -m comment --comment "globaleaks" -A INPUT -p tcp -d :: --dport $PORT -s ::1 -j ACCEPT
-                ip6tables -m comment --comment "globaleaks" -A INPUT -p tcp -d :: --dport $PORT -j DROP
-            done
+    if [[ "$TOR_SANDBOXING" -eq "1" ]]; then
+        declare -a PORTS=("80" "443")
+        for PORT in "${PORTS[@]}"; do
+            iptables -m comment --comment "globaleaks" -A INPUT -p tcp -d 0.0.0.0/0 --dport $PORT -s 127.0.0.1 -j ACCEPT
+            iptables -m comment --comment "globaleaks" -A INPUT -p tcp -d 0.0.0.0/0 --dport $PORT -j DROP
+            ip6tables -m comment --comment "globaleaks" -A INPUT -p tcp -d :: --dport $PORT -s ::1 -j ACCEPT
+            ip6tables -m comment --comment "globaleaks" -A INPUT -p tcp -d :: --dport $PORT -j DROP
+        done
 
-            # All outbound connections from GlobaLeaks goes through Tor except of allowed and enstablished connections.
-            iptables -m comment --comment "globaleaks" -A OUTPUT -m state --state RELATED,ESTABLISHED -m owner --uid-owner globaleaks -d 127.0.0.1 -j ACCEPT
-            ip6tables -m comment --comment "globaleaks" -A OUTPUT -m state --state RELATED,ESTABLISHED -m owner --uid-owner globaleaks -d ::1 -j ACCEPT
-            iptables -m comment --comment "globaleaks" -t nat -A OUTPUT ! -o lo -p tcp -m owner --uid-owner ${USERNAME} -m tcp -j REDIRECT --to-ports 9050
-            iptables -m comment --comment "globaleaks" -t filter -A OUTPUT -p tcp -m owner --uid-owner ${USERNAME} -m tcp -d 127.0.0.1 --dport 9050 -j ACCEPT
-            iptables -m comment --comment "globaleaks" -t filter -A OUTPUT ! -o lo -m owner --uid-owner ${USERNAME} -j DROP
-            ip6tables -m comment --comment "globaleaks" -t nat -A OUTPUT ! -o lo -p tcp -m owner --uid-owner ${USERNAME} -m tcp -j REDIRECT --to-ports 9050
-            ip6tables -m comment --comment "globaleaks" -t filter -A OUTPUT -p tcp -m owner --uid-owner ${USERNAME} -m tcp -d ::1 --dport 9050 -j ACCEPT
-            ip6tables -m comment --comment "globaleaks" -t filter -A OUTPUT ! -o lo -m owner --uid-owner ${USERNAME} -j DROP
-        else
-	    # Enable enstablished connections, new connections on used tcp and udp ports
-            iptables -m comment --comment "globaleaks" -A OUTPUT -m state --state RELATED,ESTABLISHED -m owner --uid-owner globaleaks -j ACCEPT
-            ip6tables -m comment --comment "globaleaks" -A OUTPUT -m state --state RELATED,ESTABLISHED -m owner --uid-owner globaleaks -j ACCEPT
-
-            declare -a PORTS=("25" "80" "53" "443" "465" "587" "9050")
-            for PORT in "${PORTS[@]}"; do
-                iptables -m comment --comment "globaleaks" -t filter -A OUTPUT -p tcp -m owner --uid-owner ${USERNAME} -m tcp --dport $PORT -j ACCEPT
-                ip6tables -m comment --comment "globaleaks" -t filter -A OUTPUT -p tcp -m owner --uid-owner ${USERNAME} -m tcp --dport $PORT -j ACCEPT
-            done
-
-            declare -a PORTS=("53")
-            for PORT in "${PORTS[@]}"; do
-                iptables -m comment --comment "globaleaks" -t filter -A OUTPUT -p udp -m owner --uid-owner ${USERNAME} -m udp --dport $PORT -j ACCEPT
-                ip6tables -m comment --comment "globaleaks" -t filter -A OUTPUT -p udp -m owner --uid-owner ${USERNAME} -m udp --dport $PORT -j ACCEPT
-            done
-        fi
-
+        # All outbound connections from GlobaLeaks goes through Tor except of allowed and enstablished connections.
+        iptables -m comment --comment "globaleaks" -A OUTPUT -m state --state RELATED,ESTABLISHED -m owner --uid-owner globaleaks -d 127.0.0.1 -j ACCEPT
+        ip6tables -m comment --comment "globaleaks" -A OUTPUT -m state --state RELATED,ESTABLISHED -m owner --uid-owner globaleaks -d ::1 -j ACCEPT
+        iptables -m comment --comment "globaleaks" -t nat -A OUTPUT ! -o lo -p tcp -m owner --uid-owner ${USERNAME} -m tcp -j REDIRECT --to-ports 9050
+        iptables -m comment --comment "globaleaks" -t filter -A OUTPUT -p tcp -m owner --uid-owner ${USERNAME} -m tcp -d 127.0.0.1 --dport 9050 -j ACCEPT
         iptables -m comment --comment "globaleaks" -t filter -A OUTPUT ! -o lo -m owner --uid-owner ${USERNAME} -j DROP
+        ip6tables -m comment --comment "globaleaks" -t nat -A OUTPUT ! -o lo -p tcp -m owner --uid-owner ${USERNAME} -m tcp -j REDIRECT --to-ports 9050
+        ip6tables -m comment --comment "globaleaks" -t filter -A OUTPUT -p tcp -m owner --uid-owner ${USERNAME} -m tcp -d ::1 --dport 9050 -j ACCEPT
         ip6tables -m comment --comment "globaleaks" -t filter -A OUTPUT ! -o lo -m owner --uid-owner ${USERNAME} -j DROP
+    else
+        # Enable enstablished connections, new connections on used tcp and udp ports
+        iptables -m comment --comment "globaleaks" -A OUTPUT -m state --state RELATED,ESTABLISHED -m owner --uid-owner globaleaks -j ACCEPT
+        ip6tables -m comment --comment "globaleaks" -A OUTPUT -m state --state RELATED,ESTABLISHED -m owner --uid-owner globaleaks -j ACCEPT
+
+        declare -a PORTS=("25" "80" "53" "443" "465" "587" "9050")
+        for PORT in "${PORTS[@]}"; do
+            iptables -m comment --comment "globaleaks" -t filter -A OUTPUT -p tcp -m owner --uid-owner ${USERNAME} -m tcp --dport $PORT -j ACCEPT
+            ip6tables -m comment --comment "globaleaks" -t filter -A OUTPUT -p tcp -m owner --uid-owner ${USERNAME} -m tcp --dport $PORT -j ACCEPT
+        done
+
+        declare -a PORTS=("53")
+        for PORT in "${PORTS[@]}"; do
+            iptables -m comment --comment "globaleaks" -t filter -A OUTPUT -p udp -m owner --uid-owner ${USERNAME} -m udp --dport $PORT -j ACCEPT
+            ip6tables -m comment --comment "globaleaks" -t filter -A OUTPUT -p udp -m owner --uid-owner ${USERNAME} -m udp --dport $PORT -j ACCEPT
+        done
     fi
+
+    iptables -m comment --comment "globaleaks" -t filter -A OUTPUT ! -o lo -m owner --uid-owner ${USERNAME} -j DROP
+    ip6tables -m comment --comment "globaleaks" -t filter -A OUTPUT ! -o lo -m owner --uid-owner ${USERNAME} -j DROP
 
     log_action_end_msg 0
 }
 
 network_sandboxing_stop()
 {
-    if ! which iptables >/dev/null 2>&1 ; then
-        echo "GlobaLeaks Network Sandboxing Failure: requires iptables"
-        return
+    if ! command -v iptables >/dev/null 2>&1  || ! command -v ip6tables >/dev/null 2>&1 ; then
+        log_failure_msg "GlobaLeaks Network Sandboxing Failure: requires iptables"
+        exit 1
     fi
 
     log_action_begin_msg "Disabling GlobaLeaks Network Sandboxing"
@@ -193,7 +191,9 @@ case "$1" in
           --user=${USERNAME}
           --working-path=${WORKING_DIR}"
 
-    network_sandboxing_start
+    if [[ "$NETWORK_SANDBOXING" -eq "1" ]]; then
+        network_sandboxing_start
+    fi
 
     log_action_begin_msg "Starting $DESC"
 
@@ -240,7 +240,9 @@ case "$1" in
         log_end_msg 0 "stopped."
     fi
 
-    network_sandboxing_stop
+    if [[ "$NETWORK_SANDBOXING" -eq "1" ]]; then
+        network_sandboxing_stop
+    fi
     ;;
   status)
     if test ! -r $(dirname $GLPID); then
